### PR TITLE
Fix new EntityManager#refresh in Doctrine ORM 2.14

### LINKED ISSUE #135: Doctrine 2.14: TooManyArguments: Too many arguments for method Doctrine\Persistence\ObjectManager::refresh
The new refresh() method signature accepts also `LockMode` flag.

However using:

```php
 $this->entityManager->refresh($reseller, LockMode::PESSIMISTIC_WRITE);
```
triggers

> ::error file=src/Helper/ResellerHelper.php,line=32,col=39,title=TooManyArguments::src/Helper/ResellerHelper.php:32:39: TooManyArguments: Too many arguments for method Doctrine\Persistence\ObjectManager::refresh - saw 2 (see https://psalm.dev/026)

### PR DESCRIPTION
**Pull request by michnovka**
Fixes https://github.com/psalm/psalm-plugin-doctrine/issues/135

### CODE REVIEW

**Comment by michnovka** [comment]
I am not sure if this is the proper fix tho. The error is complaining about Persistance interface. Any help please @orklah @weirdan ?

**Comment by orklah** [comment]
It seems to come from the Persistence\ObjectManagerInterface interface indeed. It would be this stub: https://github.com/psalm/psalm-plugin-doctrine/blob/62dd7fef85469c63739c0252c2d82151617921b5/stubs/ObjectManager.phpstub

However, we don't actually have a stub for refresh that would declare only one argument so a change here should not be needed. Unless they deployed some kind of migration path and Psalm would be confused about which signature it should take?

**Comment by michnovka** [comment]
This is the way I autowire the `$entityManager`.

```php

class ResellerHelper
{
    public function __construct(
        private readonly EntityManagerInterface $entityManager,
    ) {
    }
```
so probably, I should fix the `EntityManagerInterface` also, otherwise this autowiring will fail with psalm. This is btw the exact same approach that is used for the `EntityManager#find` and `EntityManagerInterface#find` and `$lockMode`

**Comment by michnovka** [comment]
@orklah I have pushed new fix for both `EntityManager` and `EntityManagerInterface` stubs. Tested on my code and it does resolve the issue.

**Comment by michnovka** [comment]
@orklah can we merge this please?

**Comment by orklah** [comment]
Thanks!

**Comment by michnovka** [comment]
Thanks for merging. Can you please release at least a point release?

**Pull request merged**
