### PR TITLE
Improved template support on ServiceRepository

### PR DESCRIPTION
**Pull request by SCIF**
Don't need to type hint of a template `ServiceRepository` anymore. Template class will be obtained from second argument `class-string`

### CODE REVIEW

**Comment by SCIF** [comment]
I believe the rest of failures are not introduced by me :)

**Comment by SCIF** [comment]
@weirdan , could you please take a look and let a feedback? Thanks!

**Comment by SCIF** [comment]
Ough. Base branch is `1.x` and not `master` anymore. Also, doctrine bundle has the proper template notation [since 2.3](https://github.com/doctrine/DoctrineBundle/blob/2.3.x/Repository/ServiceEntityRepository.php#L32) so the plugin stub should not be loaded.

**Comment by SCIF** [comment]
Ok, apparently, tests don't have some notation these days. I'll rework accordingly

**Comment by SCIF** [comment]
Most of issues occurs on `1.x` branch on local machine. And CI have been crashing for [two scheduled](https://github.com/psalm/psalm-plugin-doctrine/actions) runs in row.

**Comment by orklah** [comment]
Can you try rebasing on 2.X?

**Comment by SCIF** [comment]
@orklah , yes, for sure! [Done](https://github.com/psalm/psalm-plugin-doctrine/pull/100)

**Comment by orklah** [comment]
You have to change the target of your PR in github too. IIRC, you have a button below the title

**Comment by SCIF** [comment]
> You have to change the target of your PR in github too. IIRC, you have a button below the title

Yes, I know that way but I don't really understand whether 2.0 will be released soon or not. That's why I want to save the code from this PR. ServiceRepository stub in 1.x is worse than one provided by doctrine so we gonna use my own fork until 2.0 is released.

**Comment by SCIF** [comment]
I'm happy to close this PR if 2.x one will be merged.

**Comment by orklah** [comment]
Ideally, 2.0 could be released very soon. I just need some people testing it works as expected. I don't expect having to make changes to 1.X now

**Comment by SCIF** [comment]
Closing then, as I've opened 2.x PR already

**Pull request closed without merging**
