### PR TITLE
Connection Stubs

### LINKED ISSUE #104: Taint Sink connection->executeStatement is missing
the taint sink for the function `executeStatement` is missing (the deprecated `exec` works).

example:
`$connection->executeStatement('sql '. $request->get('foo'));` 

https://github.com/psalm/psalm-plugin-doctrine/blob/b24dcfd4815eed489800e97c0b605932800aabec/stubs/Connection.phpstub#L52

### PR DESCRIPTION
**Pull request by timglabisch**
see https://github.com/psalm/psalm-plugin-doctrine/issues/104

Fixes #104

### CODE REVIEW

**Comment by timglabisch** [comment]
holy shit, it seems that there are still missing a bunch of methods.

fetchAllAssociative
fetchAllNumeric
fetchAll
executeQuery
fetchAllKeyValue
fetchAllAssociativeIndexed
fetchFirstColumn
iterateNumeric
iterateAssociative
iterateKeyValue
iterateAssociativeIndexed
iterateColumn
executeQuery
executeCacheQuery
project

may someone who is more involved in this project could look at this, too?

**Comment by timglabisch** [comment]
it seems that the failing tests are not related to this pr?

**Comment by timglabisch** [comment]
there are also more changes.
for example 

`string $query` changed to `string  $sql`
https://github.com/doctrine/dbal/blob/4.0.x/src/Connection.php#L945

it also was  just $query (https://github.com/doctrine/dbal/blob/c2b8e6e82732a64ecde1cddf9e1e06cb8556e3d8/lib/Doctrine/DBAL/Connection.php#L1043) and just $sql .

**Comment by orklah** [comment]
Thanks!

Unfortunately, we're kind of short in maintainer that use Doctrine regularly so we're limited to accepting PRs!

**Pull request merged**
