### PR TITLE
Fix QueryBuilder stubs

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by weirdan** [comment]
Does this fix some inference issue?

**Comment by enumag** [comment]
It fixes a problem with classes that extend QueryBuilder. Psalm doesn't understand that these methods return the child class otherwise.

**Comment by weirdan** [comment]
I wonder if annotating it with `@return static`, which is a similar, but a bit less restrictive constraint, would suffice. What do you think?

**Comment by enumag** [comment]
Yeah, static works fine as well.

**Comment by enumag** [comment]
Do you know why are the tests failing? I don't think I caused it...

**Comment by weirdan** [comment]
Psalm has fixed the error message the tests were inspecting.

**Comment by enumag** [comment]
? Not sure what that means or how to fix it, I'm not really much familiar with Psalm yet... You should be able to fix it though, right?

**Comment by enumag** [comment]
bump

**Comment by enumag** [comment]
ping @weirdan

**Comment by enumag** [comment]
ping @weirdan

**Comment by weirdan** [comment]
Released as [0.11.2](https://github.com/weirdan/doctrine-psalm-plugin/releases/tag/0.11.2)

**Comment by enumag** [comment]
Thanks!

**Pull request merged**
